if: tag IS blank
env:
  - ARCH=x86_64
    WIX_ARCH=x64
matrix:
  include:
  - os: linux
    dist: xenial
    language: python
    python: "3.7.3"
  - os: osx
    language: generic
    osx_image: xcode10.1
  - os: windows
    language: shell
  - os: windows
    language: shell
    env:
      - CINST_ARGS=--forcex86
      - ARCH=x86
      - WIX_ARCH=x86

before_install:
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
    powershell Install-WindowsFeature Net-Framework-Core;
    cinst $CINST_ARGS python3;
    export PATH=$PATH:/c/Python37/scripts;
    cinst -y wixtoolset;
  elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew upgrade python3;
    export PATH=/usr/local/opt/python/libexec/bin:$PATH;
  fi
- pip install pyinstaller

install:
- pyinstaller --clean -F --distpath=gyb $TRAVIS_OS_NAME-gyb.spec
- gyb/gyb --version
- export GYBVERSION=`gyb/gyb --short-version`
- cp LICENSE gyb
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
    cp gyb-setup.bat gyb;
    cp license.rtf gyb;
    GYB_ARCHIVE=gyb-$GYBVERSION-windows-$ARCH.zip;
    /c/Program\ Files/7-Zip/7z.exe a -tzip $GYB_ARCHIVE gyb -xr!.svn; /c/Program\ Files\ \(x86\)/WiX\ Toolset\ v3.11/bin/candle.exe -arch $WIX_ARCH windows-gyb.wxs;
    /c/Program\ Files\ \(x86\)/Wix\ Toolset\ v3.11/bin/light.exe -ext /c/Program\ Files\ \(x86\)/WiX\ Toolset\ v3.11/bin/WixUIExtension.dll windows-gyb.wixobj -o gyb-$GYBVERSION-windows-$ARCH.msi || true;
    rm *.wixpdb;
  else
    GYB_ARCHIVE=gyb-$GYBVERSION-$TRAVIS_OS_NAME-$ARCH.tar.xz;
    tar cfJ $GYB_ARCHIVE gyb/;
  fi

script:
- gyb/gyb --version

before_deploy:
- export TRAVIS_TAG="preview"

deploy:
  provider: releases
  draft: true
  file_glob: true
  overwrite: true
  skip_cleanup: true
  api_key:
    secure: QFIqvSfIVtk6AUOfBXXHlSJh7vA09fBpg09A3F7URYXd5baAshVVnKEh3fiRftQccgCAn7H4npjRfo7uxWDr3lD1l7KbvD6LbwjSFeF1X1gD1+d6q7V8umGMgWowQEZnbbYeNxoPwEs0y/0MWyAGsWO/HD6z96PcqhYLsBUVVRsw9KUt5d5m92xTFzLWyoyE29x6dRg8kRoYbxHKaOBpzLkZiADWF3OawuSa/nhxji6uKN846gutfsaWRC/+v9mz7Z2zjAbSmo/J34cloEbSCCsDRjBNuOTptnrkxaA/g/xW/IQIMuNMzZkcDAsUYArK53u3ib4nJaOcxn7L+QmADp9Cp7puxZPKuYuMeEZOqmZ9L/F2U5BE+3vQnlbVB9aNP1NGQmwGkMqkSx0bbSch+ar0v+lOILPv3rnOZstTkzOcRuf3I+uPeCb9hL4oX69XuF9FeMl2H+Js2JhR52R54OjGJhwfZsSD1QbvjtZih3a5k+dPS2qCRnn8xzLX8wOVGqWLJpxBdE3gXMEexEtWx2h0m0uW+qyls0+RuywNCnukGygkCL3WDLHt3t9TyxbsBGvtlusV+wPVanUnVfFptvn8K2RY5fpVoWUmmGd6pjH9vMag0kfsHUVYmHPcC1nE0isBuzYpH8W0Hfnk78LqfxVHwhzMHVLo2OhhIre0gY4=
  file: gyb-$GYBVERSION-*
  on:
    repo: jay0lee/got-your-back
