if: tag IS blank

env:
  global:
    - secure: "kZxfHvKUI4pGz3a7RsTJldjPXj7pYqNMCQW5nOf/sZQV1+CqgUSDDkD/YQ0FrKG7UBYeccIZaIgeEicZlsfp6s3AEKAJ2jRd+xtKJ2zsOdExyE4WQNZB88H0OD9no1I3xUZg2qaHPa+tLn9I5EGfe8+mbFhN2xQitHgBnwu9pBjA7c0VGs8akeVwc0aOV6rd6LDmtveR0dpY9OKduF5p9zE6+0nL6CIXcW0QkUts6zatTHIttKPyjZYrW16Is2pVP0vJIxjUeenbF4PXuNAlXYgToW9eC6vyQ7emtoWS/DKX4ycBvENgvRALUbnwK+DS/afQb+UlL9REi1Wd3gAJf84N/kX4wRU6RFicgKJe2g6xi4URzRY6lTfxFbPlWxOePG0aR5MyjBfhrnC7Y6Arz48lxMfii4XFfePz+cSjxYBs+blqtp+Jd1QBJUwtXB4egXZMB/crRl2KA6GBx2pjdp4cCGwBEbXarCorGpmXn/6ArI3d1IL03IoipEhnuBdskoxNRdoPOcBI8U0lZs1NcEozLqWs8hKzhs7x3/Eg4At0WfnreQPo/QRvigNB7ITUcB39OrX8FRnZfuw0+Dy3hT9JYqWJxySHd+/qwhCd0kacU11qB2a+w1wLFl/Qh3w+wfeW5RcXMBchLJkcmx9dGhqX2jDn8XdlNi55UdZ0t5k="
    - secure: "LFax8UVeuoWDZOHJczyDV1SCGKvvjr8Luug6938J7hWqmoHJmEhn58sj2/eVu3/cz2Ja0CW0USFziVeVIAB7X5FNLWvn2JZDKl1FDeEto2BwSEjXDQxJD7iWzU2qIKIaVRuG7GEsHCo44qFrknbO5CZe48fIc84qf/E7owaWZtfJb3MCfWP6jlylnjn9N6Hu0u69p8FPqko2CJrNP9LkO2jjQJ3olC9l2A1G+V//G/ZltnkYeScf+Pqkia88fNGgDguRwMRK5uZN2Yq2yyS4V3K/WXkJMEzTdFhjxNNh3WhokbEg/tIJ5u9aXnjuCQBorCGSt1GLYlUQ6lyzMaXV4TXk+3C2wUfu+q1zwjuWwx8UJjALGKJ2VFsPWOSeJsIMIqYKqeJnAxCJgGQVvzm0PYnXwPkbdAAjWtYa6ZjEl2Fkcw2fRzKXBxH9YkBiTjGmYfG+RYzwi31halz6mynk5vUsXzJUE2zOkIwHh5LuHq3IxTjibNly07RE91GUkgEkiXVB3Yzk9WZMIpDAQjahJ4kBrWI81dLYact3G47q3NZ0DQroT9hX1VrlGh36Xm5LFlgIoSkGZmk16MPpHLuJOmyClN8QhX+V0rRIdZXckFj+ErCOcw/cBNrSTyWlwb4TgT0fvC1BlTxZ89i+ZEvzI4gBdPzRKuITFBv9vpLwUmc="
    - secure: "B1p5DzQ7o4pdJK2zHhOUqRr515QjG7sqKml/du4aSGel6v59MO6fe05iBtrSj+ToNXnpuzh2PKlueAI1ChU0Kpo2WVuBE63J+cSguWxrkvyyqnvixspLD0EglCwLv6t6zWNgP1xNl9Tg7x5ecw94JNXG7+k6aDs7dvEUnqpcIEouikFX/LIszbDJv3u6e3WJj2wjwLd1VJjZybD4am1RSysl4nbFTjLmkiSciIIDOGGj5Sk4hMeObZQp2UiEyu+bkM9j7/fD3HOdW4LhXLwSj7gYXcJ/5YMdoh9UNkGaDkFgJGzKbxDNq+PTc8vEmevf5Po9iLAPk3UDzZB9IS1k3nKx5QdTb5y2Z0pklP740UEX90DpWRZD5b3IImoLLn9cj9nzn5b33uIwsrb7yBxm7U+x6FoyWkQC20Gj+oTm2uc6Onrol8nvpQ1G7yS6l2KKGEUE86GaMC7OUwD8F6zJeQmFHc5182Kj4w+lFZ8MCNTXdR1UhroyAGe/eSiFCdl6y60hUW15PDGnffh2/AjqW2bGJiDNB2pc/uOk2RNZlyLEKwMwGm4h3dRVtgKd2MnK/kQAQlQTu8e+mWF8jebNHwNkmJJGTO+oFb9+Wl7aDG3Hi9OxWciSvCFO3s20bQmU1hTmV4xj4HE2ou9d+GV1PrbheYzCwGknrhytFwBQp8Q="
    - secure: "R+3jBFHnjvu6eVm7uElVJUDd+04umFltRxEatn5qslo4eqvc7RtaJcTdYmNTDkvHEaGStGGSA9zMjqfAfFGwAwTaNKtVBx8UZdAUaXHJd7MuWlQk3J4AY6N9et8gBugXP1st1qYw6LmhS9Tc2hZef6KLrCtTJt2IwClSO6Wu9QVGY3vGA/esTvP8wHwHYxPn92jgrP3kH5MeB1jotmdX99zu6MenfSPJnMeK+zE1dU2eUbivkO02UfmVJmjiehd4dPIrV0+D7hyQ8jpCoI9oX4xFhiAXrOlE5EGNzr9+4ndtGArhfx1dMOeHfn5JYcQVB6bG9SRwzO+NWrNUKfchPGeROq9sJBBbv72e42aqpPaoMlQ/rJD3JYGIx0rRFGaVeVYVDuZdFICZ54ZVWTfDfeQPnAg7mPnVM97hRZrIfXnZe6TLvvGxCUTybk+xU/pL8pYxLsyWY3PNjaxT6Z5IhONO/5t4dQ4zGCkyAa7eGKkz8G+r5Lr2YeyknlbJwSPdg4E1qihWYFvTNMoPoBMvNG/3GVqicWgWvUovUjI5c3Z1cy7GQ01Slu1KUHH0naxdFRRNV7swFMlPeOcS5QiDzk5Kp0spsSn8beMGjzBOaTgh8WtTOT8WDzR8sCm/sBEuuegEZplXB7+/vEXc+r5j7zvSU/gJ+dghCppyitF61iA="
    - secure: "N+TLP2/GHs7Byk6MvWOsMbE+yNAA8H1NlmClhc3F1qkkhMEUYSL+8678SFqLc7+nwAkZuo0k/X7DkCBqqvRBit9nb/vnwhtkA0KEJTJXhlPTI0KNnGPWtqpkHKK2pQi8ugIXymoLNvHw1pwQbk1pLpHeT+utsadlRhM+uDl4ZDQX0HXyl6k4qggJGHWLEIeHGM+tVEF7OJA/neT18+H7YfFxS0clAJX1MaeSDHetSeZl0/pyRmTAEvM0QTTfJ/08jf9HSXpdZJAPKhWdrF0K86KO0SkEEdNFgEWlTyO1iIfWyankKRy2RWXuGMDooje+i6UElEKIF6csnvAj4C+WLknf3bwH8wnt0w2/szjJ7PM6/dOrPYkWOa5Zz0nrvusTASnV0PWZd/Yiet0NOBIuLuxG7MCUnKg8u2qCZpcEBc3+hWPQ6MKTi199hTIBX2a5oGl1xyK0+vRFzIF2YHhWtt38iVo0zh3wb/xrzLx66HrokUN9XIQNVFJ71KCjOrDUHKp8i76cpw38kw+uO5SPJ6lZCKZYfnYty/93ZFGTIUjLgZdhr/KAFihAUYf5slJNUjKzBZtH3tYk7SJeDFYZTOgCqEnYmWLzaBsPxAREct0xk27Ms7rbVXs4aEfJz7KbSRfTfkq58sx95nNhbBI1VD7uRHrJj8/MD9cmmGigSIg="
    - secure: "anpOHuH8Cyw8VLoW7Wjmh+d8HJ0pHfZuC5Ll1TdppP+7P4A0dayj3in90+10cxjtAcOE1vEQP0A8hwjgwsXWxmOauO7uSqHYQsOytE1ULRpVZp+jU6ZjVbHsI9nwmVGG/pjbb4lA5y1jNjlRez+jO6uK81dBbX5NVuHpglnHGD2Cwim+SC4HYeY6b/NzvtdoXwgZKW/P7vdfALAYYBOn0IKFf5wO9ACHF1bj/1LXfcc9JeEOCuNJm7GgSdMXegF11XtC/TaAZ9i/pQ+TM7HeQ4qRBf5doNCO3l2pvINmYjtU2/o5wyHi11qaCydy5yyn9X1ryS17+tne9AfKWCS4Dnrny5jtd22nZMzua5l4B4jKFoO9p/pcFYWfcbl+3gPWqbfbkm4x6rZUwiztD60T/uTHSNmHbxExom8X7ikcezpdc1SjrAGrRsqhWLcaY6N8eV3mwxNvhAMNMMpypQkTmYwSZnigYJFpoHDWwSEyH7E6zpeqT39GbWcu6yABAWNwvwqc2ll1oDrn0NJ6Ds5d6uRpNGVn42UuNNB97nuCh+y6LBI3N/x0rBOOJ3+jD2OmGSo1gR1tzDADx1L7qa6+G20BuLr64hGnUoFEJRc3rK057lb3BmhAnVhEDMW6xiOUoISq1J3OSEpLPUlVb81DdzMttC/eJH8aNtv3Fd8glRk="
    - secure: "j9FxB3GNXLd/9MuVFTRG5l1ti95f4bztkKTb8Fzum/ZKdb70FncXh33m01zdJtqQ/ozvEOlAo7Nhsh1VKXJMK72QS4E8EKAKkhXNripTCBlqaelQ7wTi7TXTop0oWxSPotOb9nUWo/5Ip/ufQRre6vGC3uiKYQAZTnxy1XMD8F++i/wO0MNKzqDdnf7gYVzOhbHmgbtkd4H0+uismx8mCvAdIFP95hPMc2su8nybdBUL3zVvrahIshudSQg4BEZxQekLcR6iTSv9baJE6Yl+mY3HH5XS03LJzmI2lnX523gwNugenKHlauzveh2oIoP7m1RZ74HdL7Zia3nTPjuDaLoy6XFE21AtPeJBjeJdJ8WeCsFDeffvQzqSXM2RH/Mzk6/Ua/E/BrjNik7pK6qIK4UL5Q6uOKtVRI5smzMVeakOX4gkGy6driCQsFwzjRRZn/dT8BP3u/pvLloN2ePFH2BPUgwIvjoW2PNdwuko/K4LzlNpqkjwszVT5mdEi2/btZpckCS45OiDa7+MigVBJTF2JV71vgHccwESC6bvGVItZ2SNM6li4hc+EkdEg6CvdR3TGtTUk7ySVQGlHZoC9xaij8oWl/ijGG3UXiItPJ2gm3eWSrW326NAEzKH/fIR9dwIHbbmDz8CqF5pZBNVl5dEMfnqZ086mp3SZmuCjTM="

matrix:
  include:
  - os: linux
    name: "Linux Ubuntu Xenial 64-bit"
    dist: xenial
    language: bash 
    env:
      ARCH=x86_64
  - os: linux
    name: "Linux Ubuntu Trusty 64-bit"
    dist: trusty
    language: bash
    env:
      ARCH=x86_64
  - os: linux
    name: "Linux Ubuntu Precise 64-bit"
    dist: precise
    language: bash
    env:
      ARCH=x86_64
  - os: osx
    name: "MacOS Sierra 10.12 64-bit"
    language: generic
    osx_image: xcode9.2
    env:
      ARCH=x86_64
  - os: windows
    name: "Windows 64-bit"
    language: shell
    filter_secrets: false
    env:
      ARCH=x86_64
      CINST_ARGS=""
      WIX_ARCH=x64
  - os: windows
    name: "Windows 32-bit"
    language: shell
    filter_secrets: false
    env:
      CINST_ARGS=--forcex86
      ARCH=x86
      WIX_ARCH=x86

before_install:
- source travis/$TRAVIS_OS_NAME-$ARCH-before-install.sh
- $pip install pyinstaller
- $pip install -r requirements.txt

install:
- source travis/$TRAVIS_OS_NAME-$ARCH-install.sh

script:
- mkdir gyb-test
- cp -rf gyb/* gyb-test/
- export jid="$(cut -d'.' -f2 <<<"$TRAVIS_JOB_NUMBER")"
- export gyb_user="gyb-travis-$jid@pdl.jaylee.us"
- export gyb_group="gyb-travis-group-$jid@pdl.jaylee.us"
- export gyb_user_file="gyb-test/$gyb_user.cfg"
- cat travis/cfg_template.json | python travis/svars-write.py &> /dev/null
- echo "This job will use $gyb_user"
- gyb-test/gyb --version
- gyb-test/gyb --version | grep "Python 3\.7\.3" # we should be using Python 3.7.3
- gyb-test/gyb --version | grep TLSv1\.[23] # we should be using TLS 1.2 or 1.3
- gyb-test/gyb --version | grep travis # travis should be part of path
- gyb-test/gyb --action purge --email $gyb_user
- gyb-test/gyb --action purge-labels --email $gyb_user
- gyb-test/gyb --action restore --local-folder travis/samples/gyb-format --email $gyb_user
- gyb-test/gyb --action restore-group --local-folder travis/samples/gyb-format --email $gyb_group --use-admin $gyb_user
- gyb-test/gyb --action restore-mbox --local-folder travis/samples/historic-public-mbox --email $gyb_user --fast-restore
- gyb-test/gyb --action restore-mbox --local-folder travis/samples/google-takeout --email $gyb_user
- gyb-test/gyb --action restore-mbox --local-folder travis/samples/vault-export-mbox --email $gyb_user
- gyb-test/gyb --action count --email $gyb_user
- gyb-test/gyb --action quota --email $gyb_user
- gyb-test/gyb --action estimate --email $gyb_user
- gyb-test/gyb --action backup --email $gyb_user
- rm -rf gyb-test

before_deploy:
- export TRAVIS_TAG="preview"

deploy:
  provider: releases
  draft: true
  file_glob: true
  overwrite: true
  skip_cleanup: true
  api_key:
    secure: QFIqvSfIVtk6AUOfBXXHlSJh7vA09fBpg09A3F7URYXd5baAshVVnKEh3fiRftQccgCAn7H4npjRfo7uxWDr3lD1l7KbvD6LbwjSFeF1X1gD1+d6q7V8umGMgWowQEZnbbYeNxoPwEs0y/0MWyAGsWO/HD6z96PcqhYLsBUVVRsw9KUt5d5m92xTFzLWyoyE29x6dRg8kRoYbxHKaOBpzLkZiADWF3OawuSa/nhxji6uKN846gutfsaWRC/+v9mz7Z2zjAbSmo/J34cloEbSCCsDRjBNuOTptnrkxaA/g/xW/IQIMuNMzZkcDAsUYArK53u3ib4nJaOcxn7L+QmADp9Cp7puxZPKuYuMeEZOqmZ9L/F2U5BE+3vQnlbVB9aNP1NGQmwGkMqkSx0bbSch+ar0v+lOILPv3rnOZstTkzOcRuf3I+uPeCb9hL4oX69XuF9FeMl2H+Js2JhR52R54OjGJhwfZsSD1QbvjtZih3a5k+dPS2qCRnn8xzLX8wOVGqWLJpxBdE3gXMEexEtWx2h0m0uW+qyls0+RuywNCnukGygkCL3WDLHt3t9TyxbsBGvtlusV+wPVanUnVfFptvn8K2RY5fpVoWUmmGd6pjH9vMag0kfsHUVYmHPcC1nE0isBuzYpH8W0Hfnk78LqfxVHwhzMHVLo2OhhIre0gY4=
  file: gyb-$GYBVERSION-*
  on:
    repo: jay0lee/got-your-back
