if: tag IS blank

env:
  global:
    - BUILD_OPENSSL_VERSION=1.1.1d
    - BUILD_PYTHON_VERSION=3.8.1
    - PYINSTALLER_VERSION=3.5
    - PATCHELF_VERSION=0.9
    - secure: "kZxfHvKUI4pGz3a7RsTJldjPXj7pYqNMCQW5nOf/sZQV1+CqgUSDDkD/YQ0FrKG7UBYeccIZaIgeEicZlsfp6s3AEKAJ2jRd+xtKJ2zsOdExyE4WQNZB88H0OD9no1I3xUZg2qaHPa+tLn9I5EGfe8+mbFhN2xQitHgBnwu9pBjA7c0VGs8akeVwc0aOV6rd6LDmtveR0dpY9OKduF5p9zE6+0nL6CIXcW0QkUts6zatTHIttKPyjZYrW16Is2pVP0vJIxjUeenbF4PXuNAlXYgToW9eC6vyQ7emtoWS/DKX4ycBvENgvRALUbnwK+DS/afQb+UlL9REi1Wd3gAJf84N/kX4wRU6RFicgKJe2g6xi4URzRY6lTfxFbPlWxOePG0aR5MyjBfhrnC7Y6Arz48lxMfii4XFfePz+cSjxYBs+blqtp+Jd1QBJUwtXB4egXZMB/crRl2KA6GBx2pjdp4cCGwBEbXarCorGpmXn/6ArI3d1IL03IoipEhnuBdskoxNRdoPOcBI8U0lZs1NcEozLqWs8hKzhs7x3/Eg4At0WfnreQPo/QRvigNB7ITUcB39OrX8FRnZfuw0+Dy3hT9JYqWJxySHd+/qwhCd0kacU11qB2a+w1wLFl/Qh3w+wfeW5RcXMBchLJkcmx9dGhqX2jDn8XdlNi55UdZ0t5k="
    - secure: "LFax8UVeuoWDZOHJczyDV1SCGKvvjr8Luug6938J7hWqmoHJmEhn58sj2/eVu3/cz2Ja0CW0USFziVeVIAB7X5FNLWvn2JZDKl1FDeEto2BwSEjXDQxJD7iWzU2qIKIaVRuG7GEsHCo44qFrknbO5CZe48fIc84qf/E7owaWZtfJb3MCfWP6jlylnjn9N6Hu0u69p8FPqko2CJrNP9LkO2jjQJ3olC9l2A1G+V//G/ZltnkYeScf+Pqkia88fNGgDguRwMRK5uZN2Yq2yyS4V3K/WXkJMEzTdFhjxNNh3WhokbEg/tIJ5u9aXnjuCQBorCGSt1GLYlUQ6lyzMaXV4TXk+3C2wUfu+q1zwjuWwx8UJjALGKJ2VFsPWOSeJsIMIqYKqeJnAxCJgGQVvzm0PYnXwPkbdAAjWtYa6ZjEl2Fkcw2fRzKXBxH9YkBiTjGmYfG+RYzwi31halz6mynk5vUsXzJUE2zOkIwHh5LuHq3IxTjibNly07RE91GUkgEkiXVB3Yzk9WZMIpDAQjahJ4kBrWI81dLYact3G47q3NZ0DQroT9hX1VrlGh36Xm5LFlgIoSkGZmk16MPpHLuJOmyClN8QhX+V0rRIdZXckFj+ErCOcw/cBNrSTyWlwb4TgT0fvC1BlTxZ89i+ZEvzI4gBdPzRKuITFBv9vpLwUmc="
    - secure: "B1p5DzQ7o4pdJK2zHhOUqRr515QjG7sqKml/du4aSGel6v59MO6fe05iBtrSj+ToNXnpuzh2PKlueAI1ChU0Kpo2WVuBE63J+cSguWxrkvyyqnvixspLD0EglCwLv6t6zWNgP1xNl9Tg7x5ecw94JNXG7+k6aDs7dvEUnqpcIEouikFX/LIszbDJv3u6e3WJj2wjwLd1VJjZybD4am1RSysl4nbFTjLmkiSciIIDOGGj5Sk4hMeObZQp2UiEyu+bkM9j7/fD3HOdW4LhXLwSj7gYXcJ/5YMdoh9UNkGaDkFgJGzKbxDNq+PTc8vEmevf5Po9iLAPk3UDzZB9IS1k3nKx5QdTb5y2Z0pklP740UEX90DpWRZD5b3IImoLLn9cj9nzn5b33uIwsrb7yBxm7U+x6FoyWkQC20Gj+oTm2uc6Onrol8nvpQ1G7yS6l2KKGEUE86GaMC7OUwD8F6zJeQmFHc5182Kj4w+lFZ8MCNTXdR1UhroyAGe/eSiFCdl6y60hUW15PDGnffh2/AjqW2bGJiDNB2pc/uOk2RNZlyLEKwMwGm4h3dRVtgKd2MnK/kQAQlQTu8e+mWF8jebNHwNkmJJGTO+oFb9+Wl7aDG3Hi9OxWciSvCFO3s20bQmU1hTmV4xj4HE2ou9d+GV1PrbheYzCwGknrhytFwBQp8Q="
    - secure: "R+3jBFHnjvu6eVm7uElVJUDd+04umFltRxEatn5qslo4eqvc7RtaJcTdYmNTDkvHEaGStGGSA9zMjqfAfFGwAwTaNKtVBx8UZdAUaXHJd7MuWlQk3J4AY6N9et8gBugXP1st1qYw6LmhS9Tc2hZef6KLrCtTJt2IwClSO6Wu9QVGY3vGA/esTvP8wHwHYxPn92jgrP3kH5MeB1jotmdX99zu6MenfSPJnMeK+zE1dU2eUbivkO02UfmVJmjiehd4dPIrV0+D7hyQ8jpCoI9oX4xFhiAXrOlE5EGNzr9+4ndtGArhfx1dMOeHfn5JYcQVB6bG9SRwzO+NWrNUKfchPGeROq9sJBBbv72e42aqpPaoMlQ/rJD3JYGIx0rRFGaVeVYVDuZdFICZ54ZVWTfDfeQPnAg7mPnVM97hRZrIfXnZe6TLvvGxCUTybk+xU/pL8pYxLsyWY3PNjaxT6Z5IhONO/5t4dQ4zGCkyAa7eGKkz8G+r5Lr2YeyknlbJwSPdg4E1qihWYFvTNMoPoBMvNG/3GVqicWgWvUovUjI5c3Z1cy7GQ01Slu1KUHH0naxdFRRNV7swFMlPeOcS5QiDzk5Kp0spsSn8beMGjzBOaTgh8WtTOT8WDzR8sCm/sBEuuegEZplXB7+/vEXc+r5j7zvSU/gJ+dghCppyitF61iA="
    - secure: "Z/KiHVjMQE4qh2TrHSsrSDudf6GTkbCHrj8qdEBDipD3/pWlSyhObG1Hyyx1DTY3CrOrcamWnenRr2Ox/3PkjphuKuV2exuJckgbnhxuZ9smC07EB27gV7YUtzhkDDm6xxL5zh5bHtiKYNnfbG3NjWD9gBmM2im9K9uqpw2iun2P800eF8Skol/U8JamDmdrP94tS4Ue5ylqf72VCs4bqBxFxLU0xnnGRRCCyrQYkevDpiKdEeEqoYZNU13EW53b95owhz8AeP6Mb8D/APkWmRcYm71qaXw6yETpn5CXgKZI5YccWRLDbwuZW+EVnJBRY3nt+tZrpCsodNob1pXHiVtoAW2CeuzhNxWONbjjPFLv8ipm/bZM51MRYT586R/H2EarKbyIWT6kxhpuS3kWv6vDYkjkjnHXI+gEDL2nz+74bEb99P4nYg1Qxm1YOYZ4u/qSVCjt71VlvUIHO0AJMDEvxJ+Lt6TZm9f+4uNg4yWvmSFcXI5qjbX9EW1KCBXgxvFcSTpmDch6R9GJHtdkUHrimIqJKRkimlmP949MCWsmx0Utg1up6gc1HpyAbk5S7cC0qyePf4eLlX2HW2soxCcC62SvctSwZYpAYYJjv0gdT+i1XknNi2SsU3HQx4FoK6M07eNk/yI1t8oki9BXrVIKeGCXrp8pEv5MKDTN7bo="

    - secure: "anpOHuH8Cyw8VLoW7Wjmh+d8HJ0pHfZuC5Ll1TdppP+7P4A0dayj3in90+10cxjtAcOE1vEQP0A8hwjgwsXWxmOauO7uSqHYQsOytE1ULRpVZp+jU6ZjVbHsI9nwmVGG/pjbb4lA5y1jNjlRez+jO6uK81dBbX5NVuHpglnHGD2Cwim+SC4HYeY6b/NzvtdoXwgZKW/P7vdfALAYYBOn0IKFf5wO9ACHF1bj/1LXfcc9JeEOCuNJm7GgSdMXegF11XtC/TaAZ9i/pQ+TM7HeQ4qRBf5doNCO3l2pvINmYjtU2/o5wyHi11qaCydy5yyn9X1ryS17+tne9AfKWCS4Dnrny5jtd22nZMzua5l4B4jKFoO9p/pcFYWfcbl+3gPWqbfbkm4x6rZUwiztD60T/uTHSNmHbxExom8X7ikcezpdc1SjrAGrRsqhWLcaY6N8eV3mwxNvhAMNMMpypQkTmYwSZnigYJFpoHDWwSEyH7E6zpeqT39GbWcu6yABAWNwvwqc2ll1oDrn0NJ6Ds5d6uRpNGVn42UuNNB97nuCh+y6LBI3N/x0rBOOJ3+jD2OmGSo1gR1tzDADx1L7qa6+G20BuLr64hGnUoFEJRc3rK057lb3BmhAnVhEDMW6xiOUoISq1J3OSEpLPUlVb81DdzMttC/eJH8aNtv3Fd8glRk="
    - secure: "j9FxB3GNXLd/9MuVFTRG5l1ti95f4bztkKTb8Fzum/ZKdb70FncXh33m01zdJtqQ/ozvEOlAo7Nhsh1VKXJMK72QS4E8EKAKkhXNripTCBlqaelQ7wTi7TXTop0oWxSPotOb9nUWo/5Ip/ufQRre6vGC3uiKYQAZTnxy1XMD8F++i/wO0MNKzqDdnf7gYVzOhbHmgbtkd4H0+uismx8mCvAdIFP95hPMc2su8nybdBUL3zVvrahIshudSQg4BEZxQekLcR6iTSv9baJE6Yl+mY3HH5XS03LJzmI2lnX523gwNugenKHlauzveh2oIoP7m1RZ74HdL7Zia3nTPjuDaLoy6XFE21AtPeJBjeJdJ8WeCsFDeffvQzqSXM2RH/Mzk6/Ua/E/BrjNik7pK6qIK4UL5Q6uOKtVRI5smzMVeakOX4gkGy6driCQsFwzjRRZn/dT8BP3u/pvLloN2ePFH2BPUgwIvjoW2PNdwuko/K4LzlNpqkjwszVT5mdEi2/btZpckCS45OiDa7+MigVBJTF2JV71vgHccwESC6bvGVItZ2SNM6li4hc+EkdEg6CvdR3TGtTUk7ySVQGlHZoC9xaij8oWl/ijGG3UXiItPJ2gm3eWSrW326NAEzKH/fIR9dwIHbbmDz8CqF5pZBNVl5dEMfnqZ086mp3SZmuCjTM="
    - secure: "ObVtFT+O26vFS+RGCBklIgettshSksHvVc6GLJu5UnvkZyv+ELswFRiNLObEaY1wyywvJlWwdHSZ6Mv6YaNIPTWXalfa7AMqX6tTETqPtKv5Kr6KBv2qQpG7N1eQo/c5yAOh9sxatiV9eWmZeXD3FmP1pbO7ExTJhdLtW5Tt5bjDYq6RTaP+YCs/AI24isLDhYLd3A/GnuGckC7/MGFFSwjYQOWgAHHaob39iuhIwhDc5AgYU+jXWkGbAITyWoZqtkmUGRUl8H84vV1gKpVAl8I4wo06aFtGR63YDFLGMPLuD8DapV9bb9tkeMMzdUxVG+B/3aoH+vUnKMDtPe9mwHl7gs5oi09b1usc5tchYpTakevY4oja8k/KU1CB7YyfrkBUi36aeGCK8uJydJMR0llAMVlyJxP4w/Xr/LMTNhM++SiLIEeQ9wUzqaXhhxY+9P3gC5wXockyvj0+yLxXUqUqcWvsYrMombSsu0CnEgK0SoU0mox0Eluc6z67sUHhSDt8/PanSiyuJ2GxyxaQx1Upg4tXx4K39+kTLypSkXwDY+DfhfZ5p8jBF9GUib68Xxr7CBnpmcGSPGx15SD+JL5MRhQQgdUxTSu3y1qSwzGj5hvY/9z4QHwdo3fHnC6dQt9eDARSfTRXrfFerxxHnwnPxEjfo4OgSevCBSKS+50="
    - secure: "BJr0jsl5F5Rm4hoBW0aMYeuAboGyv2rX3Lb+FSk00PqSQXAiwCiP8JmqmcJE/UKUiI3VLtfeR7WaHY8F2gRJmVlX6+8E4eSpTT7tGUxrYFJzkMNRvObHn09k3gOE4/ii13odydpcEDg0pSHMCVjkvG5lc5jtYsYck27gY3uMUoZGq9OeG5fXQd1yGjE936RW2oryoldcB00ohHs7dvsTxYBWqhKW+ZJbiZYuGzdIz7Jr+kS0SSFLMlElmNEdnPHXgn1DXLANIMjY3w99qTf6HZG64Tx4Tl/V4lmqRM5pdYrKukWihOJmbevjHRQGx4nWXYawKnLQoPpAVfc1UcR42mJbh1tFSV2/m7wX4FrlULTZtMV5+Lg1hDxJXy7NOKFywWVVxh59fJ4a8Zf9zTvX/rGKcajfkBlUtgGYzmUpQLF3i8IclUViPEI8+Gzi0L5VJ5qQXG0P2RPQ6Z6jwVbqt4KHf40S1xC8Md2+bupiD1WUgFPG385mCbN+qXTQxAn/TZj5Q82TxbNP2895G0rbT2RTpbpZW3wxsEBEIGzECG4Jh/gjdA7U1TON90qaxy8K06StvDgBRCwO045PkN3zptT36NFKqJAf6fHz2ZRXKANCS9HAHPwsCx0T6TUrYHBYIMpOIGMR+pAUatpvKTiv3a0Z8Cd50ibt8yjpzYr4h+8="
    - secure: "MeVINmCUFlfA2OvhCJPNBDuDBIjmave3BenF68iRd1HeLoE1SJhV43dTc3IHC/acF81NyZZe3/i4BJ661SnQ65zY5HimVrzcjHpVSsyD8zs21NodW3xE2Cy+1E04D31Q2XOtux6/mOJWB16LK+66Mi0c05RoDdmw/bWnf2qDIwcxV34IlvPYinl1nFfU3tniG5yGBZt8ZVYafLVmEZFHuWTjWCiv4F495Lr8819hG9bFMZifbgK/OojDJ7oaJTwEogh01oMdCK2S/8+cqXOt7Tr9gva6tiCRQEy0bYDMRWIKHJwjwh+o/AAGEoDg0uwtUMMm7rpRITOaAEcoWYVhxebFfuhUhwTI69QhzIZiMDnQbwKhD/0LRWhnnH4Ddu1Q2D8up/OZ4FcYwrqKnqsFYK0R7FKvZ3VPPG+yR/4Oo1TcxXUKWjvNHYkAYIwfoZq33a3a55UwrKpONePF5NQXkDp2CSm/Qf71FyFAAxXzuCXlE7gQI1/lF7EJP5UJHINxhS9aqjVBrlx/Q3SKTp2+k+jD2tX/4o0aClSjFq7IPDhYR2iwy+w85OTnoS4r/ldQ1Mj9ooyp6qZLlTduIixKHssU978CWpSjwq2nQpjQYxUoRxtDoWr1myXwFQ1p6SYooLt5QLJlbB9DuMVH/phIQ/m6Fg8vVoNmE5LLINOzvsc="
    - secure: "AxTV3RvrCuwy53NqUFyVJKt/ZDtQrO8odPDQ2DW5tBeLzyNRjbL52egptJfxBo8eEvaP/PdzlfEkPP0LD6rt0eo2+EGkxJz0zL85ssMTGhjxiFJI7DW8QIE3IKq5K9VxZxNnOGyWH+eUuiSNiFB5aTs/sw5iCZVqUDyhF2OJ8XRhLtNvbrn3EB32kkBrEiXUwYXMOsO7HS+bb9ijIHZfCRbq5UUgTEjON9BfjcfquM43erUuSXBB1dD76aCRh1ehApvetVTzZR0BJx8kHUefJMSwT0GEDRDqxtSBziWQu7t80P3b4b70JJ0pmSIBw7DbJ9KCgtMpkssCA7BzGlXVcM84Qlwps+IMAC3iCgdCp7Lh0gSGTsTNupc7uYmcJaOA/RgND8/QzNR2Kicck9RL9vtBHl0ZvRbKhpwoEhwOxf6M/j1PM7ECv2xik9jkia4wEPUqU6HeeCM/RXTYpUg6VorOOAnfY1vqZF6Iz+2drHDfwQsQkx35Bo2972W1fVtvaMxdAgfddgeT7VPMCJyFaAtHUGEv5Tm1bGcv5oHZwmRI4cCMbaRm5sIfeJRMcLodPKsrLWXU3rzJVpeks8pWDbOO/w3Xp1HAwQrkCF1ZJsRQkA5XfgsmTkqn0h31RyzFiz2rBBaDi7e0ANiCYrJUEOhqTvPdgJqRaxcxHBEBhj4="
    - secure: "IIAByDZ99/O4DHuZJ3Ztujd56KsR1QSJt9ZF5P9yIGlKHnwv90n57jW0JnDgadoNGyXVyifLB5Kjb4gKUwOui6xrbikctUhBybANR3Y8e5fxO1nd7ZYK5fRrRGzhfoERW8dO3KC2Wvo1ymmzG36jvdjrN7aAjtFwfRivKshLN1WVN8ZZqiGBROR2BOdQ3fBsAetocSre8u5iYlfCXl5rIEAaQuTD6wk23VouMndnzaplSt5hbN8i29Mdu1/1ZR0PC6JM3iJu/YchItOpf7ZW7nWFMH4MBcWmRTmEQga8+BN7c8EO8YdRsWZgGWb0ycdesjRXxhXTB5g/Hns8mHmhyy3LOk1mBLqlnUoRXTRF8ZyAx1SQTWGdX8XzzMXpT9yZQwsKIccu5Vh2hEbWYOYzwafklz2vKLDAbBfhZllR0NUSrpw9bMrkLxFTbhOUyIYiT3MI8iHB1AymzieKTdJBGAWkh/fAPdyJv6PYgiUIyRQui/dnQQnFobXMTfM/7NYx7qxxRBOQR3VIA2vB6Fawd+Bpo9Z2goMUGswupZQmZ866q5ZtUK8CUGfwWurZW6A0R1QMMi43O4BP2im1cTApek+u8JzD62SCDx6pDMzCH2knTMpjYv7IbC7HCPu6cj/VshSTio+/1/5ug84pXxhioYvHiJSC2ENsvhhCmtibYH4="
    - secure: "mSTW5NRqXCQFtKV5eBs6pmmzMgfRhY+YIykzjh+YVb+AxW4wHE5fG+czC+zfew3PgTOhwgxIkrPYckuM0njGL9fqu+Gw777jLz3+qdSHClCPxeE4wKIUeC3AL5daHWkgMqGXQMyhxvG2wz3pWubA3MO1KKMXl0ic5Vg7Ag3BtlVfQ7kcYzWcQZ16Ztsf2kU9KUO2zX54TrA3Wdefq/MfqwdPwVFKlY8xzZSAuDTTz49gubGQzSUli4cVLnXwKWwKc0wUXixjpbzvd7xSoDQBZ1e+h25AxRbuMJp8UttYpIO+LJSAwVw+EWdkoWIFWctV7FA1/I7n4iZs8NoS5DlaYetuGzuYVoZMkmldWMVR5ybHU+RV5fxhv2np3q1DBQvLypKOaYs3ElWlWKtGuwnRWcmr2hlFvZDSNYrCii5+OV3ZJmTktlx+u/t255LJNOFu7Q77zLoSOWnXE9VXJjmIvECKhqTp9bIhkTEfblqxfuiivOAg/UtfiX0u65quscOPMqGBirv2dDki9fpcDrQdbxBesLekXnk11B45pOib4D0ibBYDNLJV17QnDexdQydmw4WCoOUJENIUIYe0lRofvccsuMHRpz1EvNOWDrLO6eMwGesaYcokjU2NAL+tzRw/Ew0VGUaz7WPy9yEtXemoTJyrqAFYMPXobNxK4YCg+g4="
    - secure: "l0b9wIhTRs81zaafai7JebfWmUwJefxDWKUaMQIi9UqULattwfBJlgz04IFP9zk2pnVAAJ/VC9RC4wimJt00os1QUEDvi0Tk2Rkv3DexnwujL8+8XuPpfXReFWGet9tOkDcrToN5ZkslzCxbVgTCQiLW1Qwves9oahoH89ctARy0kSQQZNw2eMrgbX7Y+gW2GhcXQt+V9SxxINPQaOKJ4g3PO2fNxkt8EenjQK8rCtKuRE+J73YLFISQc8nR3LNzkK66Oq15RYUpTZ1I1TbFP79Cwtw+67Cqp79k91t09dTXjtJCiIChRv91xOF679ZE+snOc5UvzDoYI+xMtxRaloVJDWbPS/7zLm901u45dZ2H4HpnKbZmpI88cyzLbr8ucboRP62+78Wpxxs9KIhGwVb17zVAuqBPQHOi6EmF9B/iRT8QME8PJKsqOZJK89jQKNRkNh5LAWO6WbuiRZ0F/4zVYUqiHODUPzGt10CGVYP6W0fFnHS0i9usoTCUM9BRlNIyUDgVngtt6PKYWkYC2hNEIyftWAkg2LVTFUB/OwHj/agZZX2RCK7CNLbJt3FxSHvNx3QNEzGMcPP3qxkovLlyeCpKk1TDl4Y5IsKmKhdOeATUUCWgjrL9pPNmH+eWXO7jXdsCjj7dWKedFHRVPeJaZHWm+DgkZPnPaO2wwoM="
    - secure: "b3e7aX27DRyoCctx2d9yxtAd+vM5c3RtwhIoxiB4zgq8jSb5N4NszfDLghlsa3GxSmd4YYNmAUAe+0V4qQimSMOzTHRFsXNG7LpFzZeeYoPM341VNpcMrzvI02R2b6ZysN0vb8bJri1fnL72DgAy2HJCQ7R41K1SrZsQvh70nSyo6rg406e1D1SyQPtr7JKLgByG0vCLGvWrh6qFBSPFpLauPXrrczeotP+60S2kg3lsFaynUMD9Nb9KhnctgKRp8jLdm7/Yuy4I+cXot/XVU+wGn8RQYa4i6ii1v4XN0VLpK+zXEsXEPTaG9NOon2Cy2n1uxPpdCdZ/htchptXw1iLe8WdULPvjvsaHraYPCTIB33pA0OJWkwYanC9bPWRDOw1j+9BLyWK7LkmG+O351yWNESsylYDVuNjBe+ll0tw/TzZ/Krsi6jXDPkC6UNuaCo+9zKaLJPjC4ZPFgLZDg9EmFAS99yU4BLTNHpvt00xl2Cl4quEeJ4sPeRpLJf+Mi7SiggaXLsTH0EmJf42iZ7RLML/YMWJn4LdaUnU3IkmO6Mqog0X2NlTjxhbsLS203CcGKOEyd8SCcu4tXQjjfu+PYMyQB4lyxsTgB+POjaj5LtWSRkIaqCHdBnGZkEUCSPlLGi2IAgEDnbYYJcY1GGx2wqZc+8xZuUHnp+rZ2io="
    - secure: "YYfrnynHBaeOT0P+rSdgpIeXk33hfUnSuBuMgLdA5+ju/WBAWnakm4/5GWUsUfBszMROmBpcwF5pbAQgck11nfel/ukjfs0X3cORuSmvSZQjhVIRoJImYRGLKLRlCLFoNYnnAaJUJdc2e1Rtl4u/b0AcWh5XMLAj2HbMAS4ExrgDlhUnC5JUYitMbYdhVSn/H/p4qJY15Yp44Mdw4lo6MOaAFIQvvP+Mm5oWefLHTQByqBj2cW2UPyJsXW6V924pVTYR1OQB0kpwHXJYd1DOf+YBrZAFAYZs4LSE9+4QAYyOW0dnp+wxO2UYLP8PFL39Da1LkmLFNT38j/wwBY4UVV7PUlF40aupfPMfkqA5N3/OPTLkXvubnJtrepDiB9XNqZSf9hfO/fIoMa/o7YbtE06OGsEVRMynvfeGAt9m2g60FSY/OZomX9KuQUErZ8lJI4CLj2l+iFlOQ1JRsb2IGAkmRAC2K5GeL6rlECTkoMEl6srz15u8yP3SkZ/U/9Szfr3shlSnFHRcyQW1FWsSIdYXeVRepDYVx2Bhk8hVm/QjICFU2dkPtUnNGJBZv8ZCLSPzWyLg5JlUBeG1QGa/f34DSt0HDXSfmX011Y9yBFBOOcL3J61/ktpuNDpqbJ57/oFhWaCekbK2d3MpWqbdHJHmMmOzdbT1r+zyAeHoz3o="
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/python
    - $HOME/ssl

matrix:
  fast_finish: true
  allow_failures:
    - python: pypy3.5
  include:
  - os: linux
    name: "Linux Ubuntu Bionic 64-bit"
    dist: bionic
    language: bash 
    env:
      - ARCH=x86_64
      - VMTYPE=build
  - os: linux
    name: "Linux Ubuntu Bionic arm64"
    dist: bionic
    arch: arm64
    language: bash
    filter_secrets: false
    env:
      - ARCH=arm64
      - VMTYPE=build
  - os: linux
    name: "Linux Ubuntu Xenial 64-bit"
    dist: xenial
    language: bash
    env:
      - ARCH=x86_64
      - VMTYPE=build
  - os: linux
    name: "Linux Ubuntu Xenial arm64"
    dist: xenial
    arch: arm64
    language: bash
    filter_secrets: false
    env:
      - ARCH=arm64
      - VMTYPE=build
  - os: linux
    name: "Linux Ubuntu Trusty 64-bit"
    dist: trusty
    language: bash
    env:
      - ARCH=x86_64
      - VMTYPE=build
  - os: linux
    name: "Linux Ubuntu Precise 64-bit"
    dist: precise
    language: bash
    env:
      - ARCH=x86_64
      - VMTYPE=build
  - os: linux
    name: "Python 3.5 Source Testing"
    dist: xenial
    language: python
    python: 3.5
    env:
      - ARCH=x86_64
      - VMTYPE=test
  - os: linux
    name: "Python 3.6 Source Testing"
    dist: bionic
    language: python
    python: 3.6
    env:
      - ARCH=x86_64
      - VMTYPE=test
  - os: linux
    name: "Python 3.7 Source Testing"
    dist: bionic
    language: python
    python: 3.7
    env:
      - ARCH=x86_64
      - VMTYPE=test
  - os: linux
    name: "Python nightly Source Testing"
    dist: bionic
    language: python
    python: nightly
    env:
      - ARCH=x86_64
      - VMTYPE=test
  - os: linux
    name: "PyPy Source Testing"
    dist: xenial
    language: python
    python: pypy3.5
    env:
      - ARCH=x86_64
      - VMTYPE=test
  - os: osx
    name: "MacOS 10.12"
    language: generic
    osx_image: xcode9.2
    env:
      - ARCH=x86_64
      - VMTYPE=build
  - os: osx
    name: "MacOS 10.13"
    language: generic
    osx_image: xcode10.1
    env:
      - ARCH=x86_64
      - VMTYPE=build
  - os: osx
    name: "MacOS 10.14"
    language: generic
    osx_image: xcode11.3
    env:
      - ARCH=x86_64
      - VMTYPE=build
  - os: windows
    name: "Windows 64-bit"
    language: shell
    filter_secrets: false
    env:
      - ARCH=x86_64
      - CINST_ARGS=""
      - WIX_ARCH=x64
      - VMTYPE=build
  - os: windows
    name: "Windows 32-bit"
    language: shell
    filter_secrets: false
    env:
      - CINST_ARGS=--forcex86
      - ARCH=x86
      - WIX_ARCH=x86
      - VMTYPE=build

before_install:
- source travis/$TRAVIS_OS_NAME-$ARCH-before-install.sh

install:
- source travis/$TRAVIS_OS_NAME-$ARCH-install.sh

script:
- export jid="$(cut -d'.' -f2 <<<"$TRAVIS_JOB_NUMBER")"
- export gyb_user="gyb-travis-$jid@pdl.jaylee.us"
- export gyb_group="gyb-travis-group-$jid@pdl.jaylee.us"
- export gyb_user_file="$gybpath/$gyb_user.cfg"
- cat travis/cfg_template.json | python travis/svars-write.py &> /dev/null
- openssl aes-256-cbc -K $encrypted_8664d605d46a_key -iv $encrypted_8664d605d46a_iv -in travis/oauth2service.json.enc -out $gybpath/oauth2service.json -d
- echo "This job will use $gyb_user"
- $gyb --version
- if [ "$VMTYPE" == "build" ]; then $gyb --version | grep "Python ${BUILD_PYTHON_VERSION//./\\.}"; fi # we should be using latest Python
- if [ "$VMTYPE" == "build" ]; then $gyb --version | grep "OpenSSL ${BUILD_OPENSSL_VERSION//./\\.}"; fi # we should be using latest OpenSSL
- if [ "$VMTYPE" == "build" ]; then $gyb --version | grep TLSv1\.[23]; fi # we should be using TLS 1.2 or 1.3
- $gyb --version | grep travis # travis should be part of path
- $gyb --action check-service-account --email $gyb_user
- $gyb --action purge --email $gyb_user
- $gyb --action purge-labels --email $gyb_user
- $gyb --action restore --local-folder travis/samples/gyb-format --email $gyb_user
- $gyb --action restore --local-folder travis/samples/gyb-format --email $gyb_user
- $gyb --action restore --local-folder travis/samples/gyb-format --email $gyb_user --service-account --noresume
- $gyb --action restore-group --local-folder travis/samples/gyb-format --email $gyb_group --use-admin $gyb_user
- $gyb --action restore-group --local-folder travis/samples/gyb-format --email $gyb_group --use-admin $gyb_user
- $gyb --action restore-group --local-folder travis/samples/gyb-format --email $gyb_group --use-admin $gyb_user --service-account --noresume
- $gyb --action restore-group --local-folder travis/samples/gyb-format --email $gyb_group --use-admin $gyb_user --service-account
- $gyb --action restore-mbox --local-folder travis/samples/historic-public-mbox --email $gyb_user
- $gyb --action restore-mbox --local-folder travis/samples/historic-public-mbox --email $gyb_user --service-account --noresume
- $gyb --action restore-mbox --local-folder travis/samples/google-takeout --email $gyb_user
- $gyb --action restore-mbox --local-folder travis/samples/vault-export-mbox --email $gyb_user
- $gyb --action count --email $gyb_user
- $gyb --action count --email $gyb_user --service-account
- $gyb --action quota --email $gyb_user
- $gyb --action quota --email $gyb_user --service-account
- $gyb --action estimate --email $gyb_user
- $gyb --action estimate --email $gyb_user --service-account
- $gyb --action print-labels --email $gyb_user
- $gyb --action print-labels --email $gyb_user --service-account
- $gyb --action backup --email $gyb_user
- $gyb --action backup --email $gyb_user --service-account --local-folder sa-backup
- if [ "$TRAVIS_OS_NAME" != "windows" ]; then bash <(curl -s -S -L https://git.io/gyb-install) -l; fi

before_deploy:
- export TRAVIS_TAG="preview"
- unset LD_LIBRARY_PATH

deploy:
  provider: releases
  draft: true
  file_glob: true
  overwrite: true
  skip_cleanup: true
  api_key:
    secure: QFIqvSfIVtk6AUOfBXXHlSJh7vA09fBpg09A3F7URYXd5baAshVVnKEh3fiRftQccgCAn7H4npjRfo7uxWDr3lD1l7KbvD6LbwjSFeF1X1gD1+d6q7V8umGMgWowQEZnbbYeNxoPwEs0y/0MWyAGsWO/HD6z96PcqhYLsBUVVRsw9KUt5d5m92xTFzLWyoyE29x6dRg8kRoYbxHKaOBpzLkZiADWF3OawuSa/nhxji6uKN846gutfsaWRC/+v9mz7Z2zjAbSmo/J34cloEbSCCsDRjBNuOTptnrkxaA/g/xW/IQIMuNMzZkcDAsUYArK53u3ib4nJaOcxn7L+QmADp9Cp7puxZPKuYuMeEZOqmZ9L/F2U5BE+3vQnlbVB9aNP1NGQmwGkMqkSx0bbSch+ar0v+lOILPv3rnOZstTkzOcRuf3I+uPeCb9hL4oX69XuF9FeMl2H+Js2JhR52R54OjGJhwfZsSD1QbvjtZih3a5k+dPS2qCRnn8xzLX8wOVGqWLJpxBdE3gXMEexEtWx2h0m0uW+qyls0+RuywNCnukGygkCL3WDLHt3t9TyxbsBGvtlusV+wPVanUnVfFptvn8K2RY5fpVoWUmmGd6pjH9vMag0kfsHUVYmHPcC1nE0isBuzYpH8W0Hfnk78LqfxVHwhzMHVLo2OhhIre0gY4=
  file: gyb-$GYBVERSION-*
  on:
    repo: jay0lee/got-your-back
    condition: $VMTYPE = build
