if: tag IS blank

matrix:
  include:
  - os: linux
    dist: xenial
    language: python
    python: 3.7.3
    env:
      ARCH=x86_64
  - os: osx
    language: generic
    osx_image: xcode10.1
    env:
      ARCH=x86_64
  - os: windows
    language: shell
    env:
      ARCH=x86_64
      CINST_ARGS=""
      WIX_ARCH=x64
  - os: windows
    language: shell
    env:
      CINST_ARGS=--forcex86
      ARCH=x86
      WIX_ARCH=x86

before_install:
- source travis/$TRAVIS_OS_NAME-$ARCH-before-install.sh
- pip install pyinstaller

install:
- pyinstaller --clean -F --distpath=gyb $TRAVIS_OS_NAME-gyb.spec
- gyb/gyb --version
- export GYBVERSION=`gyb/gyb --short-version`
- cp LICENSE gyb
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
    cp gyb-setup.bat gyb;
    cp license.rtf gyb;
    GYB_ARCHIVE=gyb-$GYBVERSION-windows-$ARCH.zip;
    /c/Program\ Files/7-Zip/7z.exe a -tzip $GYB_ARCHIVE gyb -xr!.svn;
    /c/Program\ Files\ \(x86\)/WiX\ Toolset\ v3.11/bin/candle.exe -arch $WIX_ARCH windows-gyb.wxs;
    /c/Program\ Files\ \(x86\)/Wix\ Toolset\ v3.11/bin/light.exe -ext /c/Program\ Files\ \(x86\)/WiX\ Toolset\ v3.11/bin/WixUIExtension.dll windows-gyb.wixobj -o gyb-$GYBVERSION-windows-$ARCH.msi || true;
    rm *.wixpdb;
  else
    GYB_ARCHIVE=gyb-$GYBVERSION-$TRAVIS_OS_NAME-$ARCH.tar.xz;
    tar cfJ $GYB_ARCHIVE gyb/;
  fi

script:
- mkdir gyb-test
- cp -rf gyb/* gyb-test/
- export jid="$(cut -d'.' -f2 <<<"$TRAVIS_JOB_NUMBER")"
- export gyb_user="gyb-travis-$jid@pdl.jaylee.us"
- export gyb_user_file="gyb-test/$gyb_user.cfg"
  #- cat travis/cfg_template.json | python travis/svars-write.py &> /dev/null
- echo "This job will use $gyb_user"
- gyb-test/gyb --version
  #- gyb-test/gyb --action purge --email $gyb_user
  #- gyb-test/gyb --action purge-labels --email $gyb_user
  #- gyb-test/gyb --action restore --local-folder travis/samples/gyb-format --email $gyb_user
  #- gyb-test/gyb --action count --email $gyb_user
  #- gyb-test/gyb --action quota --email $gyb_user
  #- gyb-test/gyb --action estimate --email $gyb_user
  #- gyb-test/gyb --action backup --email $gyb_user
- rm -rf gyb-test

before_deploy:
- export TRAVIS_TAG="preview"

deploy:
  provider: releases
  draft: true
  file_glob: true
  overwrite: true
  skip_cleanup: true
  api_key:
    secure: QFIqvSfIVtk6AUOfBXXHlSJh7vA09fBpg09A3F7URYXd5baAshVVnKEh3fiRftQccgCAn7H4npjRfo7uxWDr3lD1l7KbvD6LbwjSFeF1X1gD1+d6q7V8umGMgWowQEZnbbYeNxoPwEs0y/0MWyAGsWO/HD6z96PcqhYLsBUVVRsw9KUt5d5m92xTFzLWyoyE29x6dRg8kRoYbxHKaOBpzLkZiADWF3OawuSa/nhxji6uKN846gutfsaWRC/+v9mz7Z2zjAbSmo/J34cloEbSCCsDRjBNuOTptnrkxaA/g/xW/IQIMuNMzZkcDAsUYArK53u3ib4nJaOcxn7L+QmADp9Cp7puxZPKuYuMeEZOqmZ9L/F2U5BE+3vQnlbVB9aNP1NGQmwGkMqkSx0bbSch+ar0v+lOILPv3rnOZstTkzOcRuf3I+uPeCb9hL4oX69XuF9FeMl2H+Js2JhR52R54OjGJhwfZsSD1QbvjtZih3a5k+dPS2qCRnn8xzLX8wOVGqWLJpxBdE3gXMEexEtWx2h0m0uW+qyls0+RuywNCnukGygkCL3WDLHt3t9TyxbsBGvtlusV+wPVanUnVfFptvn8K2RY5fpVoWUmmGd6pjH9vMag0kfsHUVYmHPcC1nE0isBuzYpH8W0Hfnk78LqfxVHwhzMHVLo2OhhIre0gY4=
  file: gyb-$GYBVERSION-*
  on:
    repo: jay0lee/got-your-back
